### ISSUE TITLE
Spelling Mistakes on Giant's Causeway Page

### ISSUE THREAD

**Issue by karlb379** [earlbishopstrail/earlbishopstrail.github.io#3]
Paragraph 1, line 4 -  forklore should be folklore
Paragraph 2 line 1 - vistors should be visitors, though this should not have an "s" (see screenshot below)

![capture](https://cloud.githubusercontent.com/assets/12081488/7399145/9100d0a4-eeab-11e4-8821-7700feaf66db.PNG)

**Comment by Dylanraff** [comment]
Thanks for the report - corrected.
