### ISSUE TITLE
Derry/Londonderry issue

### ISSUE THREAD

**Issue by karlb379** [earlbishopstrail/earlbishopstrail.github.io#4]
I believe that we should be putting any mention of "Derry" as "Derry/Londonderry". This should be consistent throughout the website, I shouldn't have to explain the reasons why.

Below are the issues that, if we all agree on any mentions of "Derry" being changed to "Derry/Londonderry", will need changed:

**About** - Paragraph 3, last word
**Derry/Londonderry** - Considering that this page is all about it, I would have thought that the three mentions would be consistent with the title,
**Bishop of Derry -** not sure if this should be changed, did a bit of research and almost everywhere I looked has it as "Derry" not "Derry/Londonderry", needs to be a consideration though.

**Comment by Dylanraff** [comment]
Personally I feel like calling it "Derry/Londonderry" in both the 'Places' section and on the page header is fine and then thereafter every other reference is 'Derry' for simplicity's sake. I guess it comes down to whatever @ConstellationStudios thinks is the best approach, if he decides to read these :laughing:.

**Comment by Dylanraff** [comment]
I guess I'll just take lead and call this closed. Things can continue to stay as they are. @ConstellationStudios can reopen this if he decides otherwise.
